[package]
name = "net-monitor"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "nt"
path = "src/main.rs"

[dependencies]
hex = "0.4.3"
clap = { version = "4.5.53", features = ["derive"] }
colored = "2.1"